; Song New song in Lightweight format (V1).
; Generated by Arkos Tracker 2.

song_Start
song_StartDisarkGenerateExternalLabel

song_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
song_DisarkByteRegionEnd0
song_DisarkPointerRegionStart1
	dw song_FmInstrumentTable
	dw song_ArpeggioTable
	dw song_PitchTable
; Table of the Subsongs.
	dw song_Subsong0
song_DisarkPointerRegionEnd1

; The Arpeggio table.
song_ArpeggioTable
song_DisarkWordRegionStart2
	dw 0
song_DisarkWordRegionEnd2
song_DisarkPointerRegionStart3
song_DisarkPointerRegionEnd3

; The Pitch table.
song_PitchTable
song_DisarkWordRegionStart4
	dw 0
song_DisarkWordRegionEnd4
song_DisarkPointerRegionStart5
song_DisarkPointerRegionEnd5

; The FM Instrument table.
song_FmInstrumentTable
song_DisarkPointerRegionStart6
	dw song_FmInstrument0
	dw song_FmInstrument1
	dw song_FmInstrument2
	dw song_FmInstrument3
	dw song_FmInstrument4
song_DisarkPointerRegionEnd6

song_DisarkByteRegionStart7
song_FmInstrument0
	db 255	; Speed.

song_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
song_DisarkPointerRegionStart8
	dw song_FmInstrument0Loop	; Loops.
song_DisarkPointerRegionEnd8

song_FmInstrument1
	db 0	; Speed.

	db 61	; Volume: 15.

	db 57	; Volume: 14.

	db 53	; Volume: 13.

	db 49	; Volume: 12.

	db 45	; Volume: 11.

	db 41	; Volume: 10.

	db 37	; Volume: 9.

	db 33	; Volume: 8.

	db 29	; Volume: 7.

	db 25	; Volume: 6.

	db 21	; Volume: 5.

	db 17	; Volume: 4.

	db 13	; Volume: 3.

	db 9	; Volume: 2.

	db 5	; Volume: 1.

	db 4	; End the instrument.
song_DisarkPointerRegionStart9
	dw song_FmInstrument0Loop	; Loop to silence.
song_DisarkPointerRegionEnd9

song_FmInstrument2
	db 0	; Speed.

	db 189	; Volume: 15.
	db 25	; Arpeggio: 12.
	db 11	; Noise: 11.

	db 185	; Volume: 14.
	db 27	; Arpeggio: 13.
	db 10	; Noise: 10.

	db 181	; Volume: 13.
	db 33	; Arpeggio: 16.
	db 9	; Noise: 9.

	db 181	; Volume: 13.
	db 19	; Arpeggio: 9.
	db 8	; Noise: 8.

	db 177	; Volume: 12.
	db 1	; Arpeggio: 0.
	db 7	; Noise: 7.

	db 169	; Volume: 10.
	db 19	; Arpeggio: 9.
	db 6	; Noise: 6.

	db 161	; Volume: 8.
	db 29	; Arpeggio: 14.
	db 5	; Noise: 5.

	db 153	; Volume: 6.
	db 1	; Arpeggio: 0.
	db 4	; Noise: 4.

	db 145	; Volume: 4.
	db 1	; Arpeggio: 0.
	db 3	; Noise: 3.

	db 141	; Volume: 3.
	db 1	; Arpeggio: 0.
	db 2	; Noise: 2.

	db 4	; End the instrument.
song_DisarkPointerRegionStart10
	dw song_FmInstrument0Loop	; Loop to silence.
song_DisarkPointerRegionEnd10

song_FmInstrument3
	db 0	; Speed.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
song_DisarkPointerRegionStart11
	dw song_FmInstrument0Loop	; Loop to silence.
song_DisarkPointerRegionEnd11

song_FmInstrument4
	db 0	; Speed.

	db 61	; Volume: 15.

	db 25	; Volume: 6.

song_FmInstrument4Loop	db 53	; Volume: 13.

	db 17	; Volume: 4.

	db 4	; End the instrument.
song_DisarkPointerRegionStart12
	dw song_FmInstrument4Loop	; Loops.
song_DisarkPointerRegionEnd12

song_DisarkByteRegionEnd7
song_Subsong0DisarkByteRegionStart0
; Song New song, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

song_Subsong0
	db 4	; Initial speed.

; The Linker.
; Pattern 0
song_Subsong0loop
	db 5	; State byte.
	db 63	; New height.
song_Subsong0DisarkPointerRegionStart1
	dw song_Subsong0_Track0, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart2
	dw song_Subsong0_Track3, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart3
	dw song_Subsong0_Track2, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart4
	dw song_Subsong0_Track4, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart5
	dw song_Subsong0_Track5, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd5
; The tracks.

; Pattern 5
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart6
	dw song_Subsong0_Track6, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd6
; The tracks.

; Pattern 6
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart7
	dw song_Subsong0_Track7, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd7
; The tracks.

; Pattern 7
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart8
	dw song_Subsong0_Track8, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd8
; The tracks.

; Pattern 8
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart9
	dw song_Subsong0_Track9, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd9
; The tracks.

; Pattern 9
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart10
	dw song_Subsong0_Track10, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd10
; The tracks.

; Pattern 10
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart11
	dw song_Subsong0_Track11, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd11
; The tracks.

; Pattern 11
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart12
	dw song_Subsong0_Track12, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd12
; The tracks.

; Pattern 12
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart13
	dw song_Subsong0_Track13, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd13
; The tracks.

; Pattern 13
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart14
	dw song_Subsong0_Track14, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd14
; The tracks.

; Pattern 14
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart15
	dw song_Subsong0_Track15, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd15
; The tracks.

; Pattern 15
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart16
	dw song_Subsong0_Track16, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd16
; The tracks.

; Pattern 16
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart17
	dw song_Subsong0_Track9, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd17
; The tracks.

; Pattern 17
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart18
	dw song_Subsong0_Track10, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd18
; The tracks.

; Pattern 18
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart19
	dw song_Subsong0_Track11, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd19
; The tracks.

; Pattern 19
	db 1	; State byte.
song_Subsong0DisarkPointerRegionStart20
	dw song_Subsong0_Track12, song_Subsong0_Track1, song_Subsong0_Track1
song_Subsong0DisarkPointerRegionEnd20
; The tracks.

	db 0	; End of the subsong.
song_Subsong0DisarkPointerRegionStart21
	dw song_Subsong0loop
song_Subsong0DisarkPointerRegionEnd21

; The Tracks.
song_Subsong0_Track0
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 61, 4	; Long wait: 5.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 5	; Note: 29.
	db 61, 4	; Long wait: 5.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 61, 4	; Long wait: 5.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 5	; Note: 29.
	db 61, 4	; Long wait: 5.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.


song_Subsong0_Track1
	db 61, 63	; Long wait: 64.


song_Subsong0_Track2
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 61, 4	; Long wait: 5.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 7	; Note: 31.
	db 61, 4	; Long wait: 5.

	db 5	; Note: 29.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 61, 4	; Long wait: 5.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 7	; Note: 31.
	db 61, 4	; Long wait: 5.

	db 5	; Note: 29.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.


song_Subsong0_Track3
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 61, 4	; Long wait: 5.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 5	; Note: 29.
	db 61, 4	; Long wait: 5.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 61, 4	; Long wait: 5.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 5	; Note: 29.
	db 61, 4	; Long wait: 5.

	db 4	; Note: 28.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.


song_Subsong0_Track4
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 61, 4	; Long wait: 5.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 7	; Note: 31.
	db 61, 4	; Long wait: 5.

	db 5	; Note: 29.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 2	; Note: 26.
	db 62	; Short wait: 1.

	db 2	; Note: 26.
	db 61, 4	; Long wait: 5.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 10	; Note: 34.
	db 190	; Short wait: 3.

	db 5	; Note: 29.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track5
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 41	; Note: 65.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 46	; Note: 70.
	db 41	; Note: 65.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 41	; Note: 65.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 41	; Note: 65.
	db 43	; Note: 67.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.


song_Subsong0_Track6
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 46	; Note: 70.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 63, 79	; Escaped note: 79.
	db 63, 82	; Escaped note: 82.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 63, 79	; Escaped note: 79.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 43	; Note: 67.
	db 46	; Note: 70.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track7
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 46	; Note: 70.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 43	; Note: 67.
	db 46	; Note: 70.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 46	; Note: 70.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 6	; New instrument: 3.
	db 41	; Note: 65.
	db 43	; Note: 67.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.


song_Subsong0_Track8
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 72	; Escaped note: 72.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 63, 79	; Escaped note: 79.
	db 63, 77	; Escaped note: 77.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 2	; Note: 26.
	db 62	; Short wait: 1.

	db 191, 86	; Escaped note: 86.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 86	; Escaped note: 86.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 63, 79	; Escaped note: 79.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0_Track9
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 157	; Note: 53.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 31	; Note: 55.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 156	; Note: 52.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 157	; Note: 53.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 157	; Note: 53.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 29	; Note: 53.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.


song_Subsong0_Track10
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 142	; Note: 38.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 145	; Note: 41.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 147	; Note: 43.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 150	; Note: 46.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 19	; Note: 43.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 145	; Note: 41.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 147	; Note: 43.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 147	; Note: 43.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 22	; Note: 46.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 150	; Note: 46.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 19	; Note: 43.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 150	; Note: 46.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 145	; Note: 41.
	db 8	; New instrument: 4.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 147	; Note: 43.
	db 8	; New instrument: 4.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track11
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 169	; Note: 65.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 166	; Note: 62.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 41	; Note: 65.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 174	; Note: 70.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 41	; Note: 65.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 72	; Escaped note: 72.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.


song_Subsong0_Track12
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 190	; Short wait: 3.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 157	; Note: 53.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 26	; Note: 50.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 147	; Note: 43.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 150	; Note: 46.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 2	; Note: 26.
	db 62	; Short wait: 1.

	db 154	; Note: 50.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 29	; Note: 53.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 162	; Note: 58.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 8	; New instrument: 4.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 8	; New instrument: 4.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 8	; New instrument: 4.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 159	; Note: 55.
	db 8	; New instrument: 4.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 159	; Note: 55.
	db 8	; New instrument: 4.

song_Subsong0_Track13
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 41	; Note: 65.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 41	; Note: 65.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 82	; Escaped note: 82.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 63, 77	; Escaped note: 77.
	db 63, 79	; Escaped note: 79.

song_Subsong0_Track14
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 41	; Note: 65.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 171	; Note: 67.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 7	; Note: 31.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 132	; Note: 28.
	db 2	; New instrument: 1.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


song_Subsong0_Track15
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 84	; Escaped note: 84.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 86	; Escaped note: 86.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 63, 77	; Escaped note: 77.
	db 63, 79	; Escaped note: 79.

song_Subsong0_Track16
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 10	; Note: 34.
	db 62	; Short wait: 1.

	db 191, 86	; Escaped note: 86.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 86	; Escaped note: 86.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 130	; Note: 26.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 2	; Note: 26.
	db 62	; Short wait: 1.

	db 191, 74	; Escaped note: 74.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 79	; Escaped note: 79.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.


song_Subsong0DisarkByteRegionEnd0
